const { contextBridge, ipcRenderer, webUtils } = require('electron');

const invoke = (channel, ...args) => ipcRenderer.invoke(channel, ...args);

contextBridge.exposeInMainWorld('sqliteScope', {
  getSettings: () => invoke('app:get-settings'),
  setTheme: (theme, density) => invoke('app:set-theme', theme, density),
  saveAppearance: (appearance) => invoke('app:save-appearance', appearance),
  chooseConverterSource: () => invoke('converter:choose-source'),
  previewCsvConversion: (filePath, options) => invoke('converter:preview-csv', filePath, options),
  runConversion: (filePath, options) => invoke('converter:run', filePath, options),
  queryHistory: (filePath) => invoke('app:query-history', filePath),
  addQueryHistory: (filePath, item) => invoke('app:add-query-history', filePath, item),
  clearQueryHistory: (filePath) => invoke('app:clear-query-history', filePath),
  chooseDatabase: () => invoke('dialog:open'),
  chooseNewDatabase: () => invoke('dialog:create'),
  openDatabase: (filePath, options) => invoke('db:open', filePath, options),
  createDatabase: (filePath) => invoke('db:create', filePath),
  listDatabases: () => invoke('db:list'),
  activateDatabase: (id) => invoke('db:activate', id),
  closeDatabase: (id) => invoke('db:close', id),
  overview: () => invoke('db:overview'),
  rows: (name, options) => invoke('db:rows', name, options),
  structure: (name) => invoke('db:structure', name),
  saveRow: (payload) => invoke('db:save-row', payload),
  deleteRows: (name, identities) => invoke('db:delete-rows', name, identities),
  runSql: (sql) => invoke('db:run-sql', sql),
  createTable: (spec) => invoke('db:create-table', spec),
  planTableStructure: (name, spec) => invoke('db:plan-table-structure', name, spec),
  updateTableStructure: (name, spec) => invoke('db:update-table-structure', name, spec),
  createIndex: (spec) => invoke('db:create-index', spec),
  dropIndex: (name) => invoke('db:drop-index', name),
  saveSchemaObject: (type, name, sql, originalName) => invoke('db:save-schema-object', type, name, sql, originalName),
  dropSchemaObject: (type, name) => invoke('db:drop-schema-object', type, name),
  attachedDatabases: () => invoke('db:attached-databases'),
  attachDatabase: (filePath, schema) => invoke('db:attach-database', filePath, schema),
  detachDatabase: (schema) => invoke('db:detach-database', schema),
  setPragma: (name, value) => invoke('db:set-pragma', name, value),
  renameTable: (oldName, newName) => invoke('db:rename-table', oldName, newName),
  dropObject: (name, type) => invoke('db:drop-object', name, type),
  emptyTable: (name) => invoke('db:empty-table', name),
  importRows: (name, headers, rows) => invoke('db:import-rows', name, headers, rows),
  integrityCheck: () => invoke('db:integrity'),
  pragmas: () => invoke('db:pragmas'),
  maintenance: (action) => invoke('db:maintenance', action),
  queryTemplates: (name) => invoke('db:query-templates', name),
  backup: () => invoke('db:backup'),
  exportData: (format, objectName) => invoke('db:export', format, objectName),
  filePath: (file) => webUtils.getPathForFile(file),
  onOpenPath: (callback) => ipcRenderer.on('menu:open-path', (_event, value) => callback(value)),
  onCreatePath: (callback) => ipcRenderer.on('menu:create-path', (_event, value) => callback(value)),
  onBackup: (callback) => ipcRenderer.on('menu:backup', callback),
  onCloseDatabase: (callback) => ipcRenderer.on('menu:close-database', callback),
  onExternalChange: (callback) => ipcRenderer.on('db:external-change', (_event, value) => callback(value)),
  onRecentsChanged: (callback) => ipcRenderer.on('app:recents-changed', (_event, value) => callback(value)),
  onRefresh: (callback) => ipcRenderer.on('menu:refresh-database', callback),
  onRunQuery: (callback) => ipcRenderer.on('menu:run-query', callback),
  onIntegrity: (callback) => ipcRenderer.on('menu:integrity', callback),
  onDatabaseTools: (callback) => ipcRenderer.on('menu:database-tools', callback)
  ,onAppearance: (callback) => ipcRenderer.on('menu:appearance', callback)
  ,onConverter: (callback) => ipcRenderer.on('menu:converter', callback)
});
