const assert = require('assert');
const fs = require('fs');
const os = require('os');
const path = require('path');
const { DatabaseSync } = require('node:sqlite');
const { parseDelimited, previewCsv, convertCsv, convertSql, prepareSqlScript } = require('../src/converter');

const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'sqlitescope-converter-'));
try {
  assert.deepStrictEqual(parseDelimited('name,note\nAlice,"hello, world"\nBob,"two\nlines"\n'), [['name', 'note'], ['Alice', 'hello, world'], ['Bob', 'two\nlines']]);
  const csv = path.join(dir, 'people.csv');
  fs.writeFileSync(csv, 'id,name,score,name\n1,Alice,9.5,A\n2,Bob,8,B\n');
  const preview = previewCsv(csv, { delimiter: 'auto', hasHeader: true });
  assert.deepStrictEqual(preview.columns.map((item) => [item.name, item.type]), [['id', 'INTEGER'], ['name', 'TEXT'], ['score', 'REAL'], ['name_2', 'TEXT']]);
  const dbPath = path.join(dir, 'people.sqlite3');
  assert.strictEqual(convertCsv(csv, dbPath, { tableName: 'people', delimiter: 'auto', hasHeader: true }).rowsImported, 2);
  let db = new DatabaseSync(dbPath);
  assert.strictEqual(db.prepare('SELECT COUNT(*) AS n FROM people').get().n, 2);
  assert.strictEqual(db.prepare('SELECT score FROM people WHERE id = 1').get().score, 9.5);
  db.close();
  const phpMyAdmin = prepareSqlScript('-- phpMyAdmin SQL Dump\nSET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";\nCREATE TABLE `users` (`id` int(11) NOT NULL, `name` varchar(50)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;\nINSERT INTO `users` VALUES (1, \'Asha\');');
  assert.strictEqual(phpMyAdmin.dialect, 'mysql-compatible');
  assert.ok(!/^\s*SET\s/im.test(phpMyAdmin.sql));
  const mysqlSql = path.join(dir, 'phpmyadmin.sql'), mysqlDb = path.join(dir, 'phpmyadmin.sqlite');
  fs.writeFileSync(mysqlSql, '-- phpMyAdmin SQL Dump\nSET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";\nSET time_zone = "+00:00";\nCREATE TABLE `users` (`id` int(11) NOT NULL, `name` varchar(50)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;\nINSERT INTO `users` VALUES (1, \'Asha\');');
  const mysqlResult = convertSql(mysqlSql, mysqlDb);
  assert.strictEqual(mysqlResult.dialect, 'mysql-compatible');
  db = new DatabaseSync(mysqlDb);
  assert.strictEqual(db.prepare('SELECT name FROM users').get().name, 'Asha');
  db.close();
  const fullDump = path.join(dir, 'full-phpmyadmin.sql'), fullDumpDb = path.join(dir, 'full-phpmyadmin.db');
  fs.writeFileSync(fullDump, `-- phpMyAdmin SQL Dump
SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
CREATE TABLE \`admins\` (\`id\` int(10) UNSIGNED NOT NULL, \`email\` varchar(190) NOT NULL, \`created_at\` datetime NOT NULL DEFAULT current_timestamp()) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
INSERT INTO \`admins\` VALUES (1, 'a@example.com', '2026-08-10 00:00:00');
CREATE TABLE \`subscribers\` (\`id\` bigint(20) UNSIGNED NOT NULL, \`email\` varchar(190) NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
ALTER TABLE \`admins\` ADD PRIMARY KEY (\`id\`), ADD UNIQUE KEY \`email\` (\`email\`);
ALTER TABLE \`subscribers\` ADD PRIMARY KEY (\`id\`), ADD UNIQUE KEY \`email\` (\`email\`);
ALTER TABLE \`admins\` MODIFY \`id\` int(10) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=2;
ALTER TABLE \`subscribers\` MODIFY \`id\` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT;
COMMIT;`);
  convertSql(fullDump, fullDumpDb);
  db = new DatabaseSync(fullDumpDb);
  assert.strictEqual(db.prepare('SELECT email FROM admins').get().email, 'a@example.com');
  assert.strictEqual(db.prepare('PRAGMA table_info(admins)').all().find((column) => column.name === 'id').pk, 1);
  assert.deepStrictEqual(db.prepare("SELECT name FROM sqlite_schema WHERE type='index' ORDER BY name").all().map((row) => row.name), ['admins_email', 'subscribers_email']);
  assert.strictEqual(db.prepare('PRAGMA integrity_check').get().integrity_check, 'ok');
  db.close();
  const sql = path.join(dir, 'schema.sql');
  fs.writeFileSync(sql, 'CREATE TABLE tasks(id INTEGER PRIMARY KEY, title TEXT); INSERT INTO tasks(title) VALUES (\'Test\');');
  const sqlDb = path.join(dir, 'tasks.db3');
  convertSql(sql, sqlDb);
  db = new DatabaseSync(sqlDb);
  assert.strictEqual(db.prepare('SELECT title FROM tasks').get().title, 'Test');
  db.close();
  const invalid = path.join(dir, 'invalid.sql'), invalidDb = path.join(dir, 'invalid.db');
  fs.writeFileSync(invalid, 'CREATE TABLE ok(id); THIS IS INVALID;');
  assert.throws(() => convertSql(invalid, invalidDb));
  assert.strictEqual(fs.existsSync(invalidDb), false);
  console.log('All SQLiteScope converter tests passed.');
} finally { fs.rmSync(dir, { recursive: true, force: true }); }
